apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"
    stdout: true
    otel:
      endpointAddress: "jaeger:4317"
      isSecure: false
      protocol: grpc
