apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-binding-service-a
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
    - name: queueName
      value: "queue-x"
    - name: host
      value: "amqp://guest:guest@rabbitmq:5672/"
    - name: contentType
      value: "text/plain"
    - name: route
      value: api/demo/hello
    - name: direction
      value: "input"
