apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub-service-c
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://guest:guest@rabbitmq:5672/"
    - name: clientName
      value: {podName}
    - name: exchangeKind
      value: "fanout"
    - name: durable
      value: false
    - name: deletedWhenUnused
      value: false
